### ISSUE TITLE
Wrapping button text to the next line

### ISSUE THREAD

**Issue by zroger49** [jimz011/homekit-infused#102]
Greetings. 
I've using home-kit infused for the past week or so I was wondering if there are anyway to wrap the entity button text to the next line. This is the current behavior: 

![Screenshot from 2021-07-09 13-45-45](https://user-images.githubusercontent.com/83769543/125079853-fe024580-e0bb-11eb-9264-25bd08734e84.png)

I would like to the whole string in the button name to show

**Comment by jimz011** [comment]
Not sure how to fix that without making the button look weird. But you could try adding a break in the text that might work. (I will check it out later tonight if I can make something like that).

Else I suggest using less columns (e.g. 3 buttons so that they are larger) another thing you can do is making the text shorter. But that doesnt seem like a real solution.

**Comment by zroger49** [comment]
> Not sure how to fix that without making the button look weird. But you could try adding a break in the text that might work. (I will check it out later tonight if I can make something like that).
> 
> Else I suggest using less columns (e.g. 3 buttons so that they are larger) another thing you can do is making the text shorter. But that doesn't seem like a real solution.

I'm already using 3 columns (I'm using your dashboard for mobile, but i was easier to take a screenshoot in the computer). 
I've tried to add a break like so: 

`'this is a \n very long string' `

and 
`
"this is a \n very long string"`

I'm guessing decreasing the font size on a button to button basis is not really possible in the framework of homekit-infused. Let me know if you figure something out
