### ISSUE TITLE
Plans to make a service to reload homekit-infused 

### ISSUE THREAD

**Issue by zroger49** [jimz011/homekit-infused#103]
Greetings. 
I was testing automation and using the reload button for homekit-infused. When that was not working I noticed the actual code on yaml only reloads the input_boolean.

```
- !include
  - '../templates/button/home-assistant-service.yaml'
  - name: Reload
    entity: input_boolean.dummy1
    label: Homekit
    icon: mdi:apple
    service: input_boolean.reload
    opacity_off: 0.8
    confirmation: "[[[ return `Are you sure you want to reload the Homekit Component?` ]]]"

```
So, I have two questions: Was this a mistake or is it a planed featured? And is there a way to reload the view_config.yaml?

**Comment by jimz011** [comment]
Well, actually HKI v3 and below had the option to reload from the interface. But since v4 is fundamentally different this is not possible.

You see, the templates will load (or not) at the very start of HA and will only be loaded once. The reason for this was simple. Purely performance. If I would make the project like it was in v3 people with slow hardware will feel a massive impact on performance since all the templates would be loaded regardless if the user wants them or not. This would ramp up loading times to a sixfold of what it currently is.

Also since none of the templates get loaded now unless you specifically define them in view_config makes sure that lovelace will only load what is required.

I did look into recreating this as a custom component which would make some of these options you want possible. But it would require me to learn JS, so in this case I have opted to continue building a dedicated app instead. Unfortunately my time is currently extremely low, and I still need to update this project for current HA versions. So dont expect the dedicated app soon. (The app will take away most annoyances since it would be dependent on your devices hardware instead of the hardware HA is running on).

**Comment by zroger49** [comment]
> Well, actually HKI v3 and below had the option to reload from the interface. But since v4 is fundamentally different this is not possible.
> 
> You see, the templates will load (or not) at the very start of HA and will only be loaded once. The reason for this was simple. Purely performance. If I would make the project like it was in v3 people with slow hardware will feel a massive impact on performance since all the templates would be loaded regardless if the user wants them or not. This would ramp up loading times to a sixfold of what it currently is.
> 
> Also since none of the templates get loaded now unless you specifically define them in view_config makes sure that lovelace will only load what is required.
> 
> I did look into recreating this as a custom component which would make some of these options you want possible. But it would require me to learn JS, so in this case I have opted to continue building a dedicated app instead. Unfortunately my time is currently extremely low, and I still need to update this project for current HA versions. So dont expect the dedicated app soon. (The app will take away most annoyances since it would be dependent on your devices hardware instead of the hardware HA is running on).

Okay makes sense. Just out of curiosity, were you looking in adapting something like browser mod for this purpose? 
(if you feel this discussion does not make sense in the issue feel free to close it and pm me)
