### ISSUE TITLE
hey, i just updated the latest version Ver2022.1.2, but got error.

### ISSUE THREAD

**Issue by codepriince** [jimz011/homekit-infused#121]
while parsing a block mapping in "/config/hki-base/base.yaml", line 2610, column 11 expected <block end>, but found '<scalar>' in "/config/hki-base/base.yaml", line 2619, column 13

**Comment by jimz011** [comment]
Hm, odd. 2022.01.2 only had theme files as an update, from which version did you update?

**Comment by codepriince** [comment]
hey, my hki was updated from Homekit Infused 2022.01.1 to 2022.01.02.

**Comment by jimz011** [comment]
Hm the file in your error has not been updated in that version. So I am not sure as to why this is happening. Did you recently add a view or some config, but did not restart at that time (so the error is not immediately apparent?). Because that could explain why it isn't working now.

For what it's worth, from v2022.01.1 to 2022.01.2, literally only the theme files have changed (they are separate from lovelace files) so I find it very odd.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by codepriince** [comment]
you are right.i added some config  before and did not restart my HA. then i update v2022.01.1 to v2022.01.2,  after restart HA, got the error.

**Comment by codepriince** [comment]
how can i solve it? please tell me.Thanks.

**Comment by jimz011** [comment]
Well start with commenting out the stuff you did before restarting/updating. Try if it starts then, if it does well at least you know where to look. If it doesn't maybe try restoring a backup (If you have those ofc, but then again with each update I stress out to people to make backups, so let's hope so 🤣)



Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by codepriince** [comment]
I have a backup file. I will try to restore my backup tonight.Thanks a lot.

**Comment by codepriince** [comment]
I have a backup file. I will try to restore my backup tonight.Thanks a lot.

**Comment by codepriince** [comment]
After retore the backup file, it works well. Thianks.
