### ISSUE TITLE
Error on every single card

### ISSUE THREAD

**Issue by dnestico** [jimz011/homekit-infused#124]
So I was editing my view and then it stopped working and would never load so I decided to re-download the base.yaml and view.config files again from the beginning, Now I'm just getting errors on every single card which makes no sense since I have all of those card plugins installed as the instructions said to install them. Please help me figure out this mess.

https://user-images.githubusercontent.com/3034555/152461189-29ea2cd0-8bad-4a96-8c61-667233ca1cb0.mp4

**Comment by jimz011** [comment]
This is most likely a cache problem

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: David Nestico ***@***.***>
Sent: Friday, February 4, 2022 3:17:13 AM
To: jimz011/homekit-infused ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [jimz011/homekit-infused] Error on every single card (Issue #124)


SoI was editing my view and then it stopped working and would never load so I decided to download the base.yaml and view.config files again from the beginning, Now I'm just getting errors on every single card which makes no sense since I have all of those card plugins installed as the instructions said to install them. Please help me figure out this mess.

https://user-images.githubusercontent.com/3034555/152461189-29ea2cd0-8bad-4a96-8c61-667233ca1cb0.mp4<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F3034555%2F152461189-29ea2cd0-8bad-4a96-8c61-667233ca1cb0.mp4&data=04%7C01%7C%7C0585d5c1f4fc43f880f808d9e78475c5%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637795378356847488%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=dGdQ%2BhsFaJmJYXFoE5%2FZ7IhHQQHR085I5HKBdmRoh9A%3D&reserved=0>

**Comment by dnestico** [comment]
> This is most likely a cache problem Get Outlook for Android<https://aka.ms/AAb9ysg>

Hi I cleared my browser cache and tried a different browser and the cards still look like that. I might have to try reinstalling them maybe, unless you know something else.

**Comment by dnestico** [comment]
Reinstalled everything and seems fixex! 😅
