### ISSUE TITLE
I literally can't figure out how this works.

### ISSUE THREAD

**Issue by dnestico** [jimz011/homekit-infused#125]
PLEASE can someone explain to me how to add some simple entities like lights or a weather card, I've changed my view code so many times and literally can't figure it out at all
<img width="787" alt="Screen Shot 2022-02-09 at 4 18 54 AM" src="https://user-images.githubusercontent.com/3034555/153164256-595650fb-2f78-40c6-87ec-e76f91ab01ce.png">
<img width="1062" alt="Screen Shot 2022-02-09 at 4 19 02 AM" src="https://user-images.githubusercontent.com/3034555/153164258-73d0c72c-cfe7-481e-838d-aebffba427ff.png">
<img width="1060" alt="Screen Shot 2022-02-09 at 4 19 10 AM" src="https://user-images.githubusercontent.com/3034555/153164259-0907e505-d633-4197-b106-72dc0d7d0bf1.png">
.

**Comment by jimz011** [comment]
The documentation is pretty clear on how to add cards to your views.

But.... you can find examples on my personal repo [HERE](https://github.com/jimz011/homekit-infused/blob/4.x.x-personal/hki-user/config/view_config.yaml).
Hold it against the documentation for (example) [DEVICES](https://github.com/jimz011/homekit-infused/blob/4.x.x-docs/docs/addons-v4/devices.md) and hopefully this will make a bit more sense to you.

If you still can't make it work I will suggest joining our discord channels, since the community and I can respond faster over there. But before you do so, please check out the links above!

**Comment by dnestico** [comment]
I will consider check these out and the discord because I've followed the guide and still can't get it too work. Thanks
