### ISSUE TITLE
[Just Thanks] no issue

### ISSUE THREAD

**Issue by jjsapido** [jimz011/homekit-infused#129]
Since you closed all my previous FRs, I had no chance to answer to your communication. Just to say thank you for your effort at addressing my suggestions and eagerly waiting for v5 :)
best

**Comment by jimz011** [comment]
Well, you actually made me look into it again. Since I usually take a pretty long break after releasing a major version (since well it is really time consuming and gives me head aches 😂 ) And I do it all for free, most people never really donate anything. Though honestly I don't do it for the money, I do it so that other people may enjoy the stuff that I made.

Everytime I take a break the stuff that I had been working on trying to find a solution for weeks/months just come to me within hours or days. So I learn from it myself as well and you have just inspired me to revisit the addons and redo everything.

I initially planned to do a header only change for HKI 5, but I decided to rewrite it because of this idea. Everything has been rewritten from the ground up and will have over 200+ new features (and even more counting the fact that you can now literally work with HKI as if it were just a normal yaml lovelace board) but will be roughly half in size codewise). I have also removed over 50 templates, only a few remain.

It gets better, I have even added a few new addons.

I will close this now and I appreciate your help/compliments.

Stay tuned as HKI videos will drop on my YT channel soon with instructions to configure HKI 5 and a overview of all the possible features.
