### ISSUE TITLE
Can't login on iPad

### ISSUE THREAD

**Issue by dnestico** [jimz011/homekit-infused#131]
Ok so this isn't a home kit infused issue but for some reason I'm trying to login on my ipad and it either keeps saying wrong username or password or when it finally does get past that it gives me an error message.

I have multiple users setup and those don't work  either, then when I try to use the MAIN ADMIN account that works on any desktop that also DIDN'T work on the iPad mini, it's too old to download the home assistant app so trying through Safari browser and even tried on chrome browser on the iPad

I don't understand why I can't login on the iPad.

![PXL_20220220_033841735.MP-min.jpg](https://user-images.githubusercontent.com/3034555/154827603-aee5040c-8dcf-4d68-8fd6-d83a706796e3.jpg)

**Comment by jimz011** [comment]
Unrelated to HKI, and unfortunately I can't answer this as it could have so many reasons.

I would also appreciate if you didn't open an issue for questions like this since there are already enough platforms where you can find answers for this.

Try the Home Assistant community forums for questions like these. Or join our Discord server.

You should realise that I am not the Home Assistant help desk. So please keep questions here about HKI. Imagine that everyone just opens tickets about general questions.

I know you meant well, so no worries  but I will close this issue now.

**Comment by dnestico** [comment]
Yup understandable, I'll open a ticket on the community GitHub
