### ISSUE TITLE
Error in Installation

### ISSUE THREAD

**Issue by helge1979** [jimz011/homekit-infused#136]
After installing i get the following error message, when i want to open the dashboard.

while scanning for the next token found character '%' that cannot start any token in "/config/hki-base/templates/popups/close-popup.yaml", line 26, column 12

any ideas?

**Comment by jimz011** [comment]
did you install lovelace_gen?

**Comment by helge1979** [comment]
> did you install lovelace_gen?

yes, already installed

**Comment by jimz011** [comment]
Do you by any chance have Dwains Dashboard or any other kind of dashboard installed?

For Dwains Dashboard you will need to disable lovelace_gen on HKI as mentioned in the docs.

If you use some other Dashboard that also leverages lovelace_gen then I dont think you will be in luck since they will need to add a function for it to their Dashboard.

**Comment by helge1979** [comment]
i did not have any other dashboard installed. can i check if something uses lovelace_gen?

Attached you find the Screenshot of the error message

![2022-03-14 08_26_08-Window](https://user-images.githubusercontent.com/21008459/158125003-8c34ffdd-4b3b-4abd-b547-8d126db6bd95.png)

**Comment by jimz011** [comment]
Is it a fresh install or did you change anything? If you did change anything I will need to know what you have done. Since this error is impossible to get when installing fresh, I'd love to know what you did.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jimz011** [comment]
Closed because no more replies have been posted.
