### ISSUE TITLE
Upgrade from v4 to v5 successfully done, but

### ISSUE THREAD

**Issue by clickme83** [jimz011/homekit-infused#139]
Hi Jimmy,

I took the challenge and upgraded from v4 to v5 and applied all necessary changes. There are still a few minor errors:

- sensor.hki_current_version shows 2022.02.0, therefore sensor.hki_updater shows 'update available'
- sensor.ha_updater shows 'update available' while I run the latest version 2022.3.5
- On my Profile Card I'am missing 'HKI Settings' and information about the server

Have you any idea how to get rid of the errors?

One off topic-question :): Which gps tracker do you use for your dog?

**Comment by jimz011** [comment]
1. The sensors are not referenced anywhere anymore (this is due to the fact that it needs to be added, but not sure how and where yet)
2. The HA version sensor has been removed entirely (this is a change made by HA and I felt adding this whole step to the docs would only make the docs larger in size whilst not being a necessary step)
3. In your profile card you can scroll the top bar, scroll to the right until you find the settings.

Let me know if your problem got resolved,

**Comment by clickme83** [comment]
Yes, thanks
