### ISSUE TITLE
Is this scrolling intended or a bug? Made a video 

### ISSUE THREAD

**Issue by henrikrox** [jimz011/homekit-infused#147]
https://user-images.githubusercontent.com/6884716/162033061-2ba9306c-0f7b-429d-857a-1fa934bd7762.MP4

When you go the subtitle view follows you down. This happens on every view. But it gets kinda crushed/squished. I have severe OCD but see where it says 9 enheter on top left. When i scroll down it follows me. Is this intended?

**Comment by jimz011** [comment]
No this is not intended. It should be sticky at the top.

It sometimes happens when setting up a grid layout (however since you have it on all views, I am guessing it is something else.

I also notice you use iOS. Since iOS uses different css names in some occasions, it sometimes requires some feedback from you guys since I don't have any iOS devices anymore.

I will look into this, I guess it is just a simple line. I will keep in touch with you and send you some stuff to try later today. If it works I will push it with this week's update.

**Comment by jimz011** [comment]
I do have the possibility to test on iOS though, but I can only do it when I know when since I need to take an iPhone from work to do that.

Also, if no one doesn't create issues, I assume it works fine for anyone. So thank you for opening this issue, so I know that I need to fix it.

**Comment by jimz011** [comment]
@henrikrox I found the culprit, it doesn't work with the HKI navigation bar turned off.

![image](https://user-images.githubusercontent.com/47046878/162064856-846113c4-fbe7-4740-ba8c-7288b011eefe.png)

Turn this on and set change the appearance to what you currently have (this should be the default anyways).
Unfortunately there is nothing I can do about this. It should work fine when turned on.

It is however persistent, this means it will also have this feature on other dashboards (this can be very useful or extremely annoying). Dashboards that set their own themes like Dwains Dashboard will not have this issue.

Btw, the sticky code for the header hasn't changed since HKI 1, this should mean that HKI 4 and lower also needed this setting to be turned on. It might be possible though that the setting was turned on by default in HKI 4, unfortunately I can't remember.

Please try it and share me your results.
