### ISSUE TITLE
Rooms/Areas

### ISSUE THREAD

**Issue by domemshur** [jimz011/homekit-infused#158]
Can I create rooms or should I wait for the areas update?

**Comment by jimz011** [comment]
Rooms and Areas are essentially the same, you can give any name to any view and you can arrange them as such.

The areas update (which I have postponed) will not drop soon, there are a lot of nice cards that can fill this gap like mushroom cards or even the areas core card. Just make sure you create the view in your HKI settings so that you can navigate to it from any of those cards.
