### ISSUE TITLE
Device counter not working for motion sensors

### ISSUE THREAD

**Issue by PaulBartelings** [jimz011/homekit-infused#186]
Hi Jim,

Thanks for the great product, I love it ;)

Have one thing, can't get the device counter to work for the motion sensors. All other counters work fine, but motion no.

# Motion Sensors (This is used in the header badges, without this the header badge won't work)
all_motion_sensor_entities:
    entities:
    - binary_sensor.bewegingsensor_achtertuin_spots_occupancy
    - binary_sensor.bewegingsensor_garage_garage_occupancy
    - binary_sensor.bewegingsensor_toilet_lamp_occupancy
    - binary_sensor.bewegingsensor_buiten_carport_occupancy
    - binary_sensor.bewegingsensor_zolder_berging_occupancy
    - binary_sensor.bewegingsensor_zolder_overloop_occupancy

And yes, I'm Dutch as well :)

**Comment by jimz011** [comment]
Your entities told me so 😂 

Anyways, could you perhaps show me what kind of state these sensors of yours show?
I think occupancy works different than actual motion sensors (since I guess occupancy counts the number of guests in a certain room am I right?).

Could you perhaps show me what the output is of their states? The counter currently only works with on and off states (or open/closed, but they will be shown as on/off in the states engine regardless)

**Comment by jimz011** [comment]
I have looked again into this, but those sensors should output `on` or `off` which is supported by HKI by default.

**Comment by PaulBartelings** [comment]
![Scherm­afbeelding 2023-01-16 om 22 11 47](https://user-images.githubusercontent.com/28623542/212766536-a79cd208-58bb-4a04-bfb9-fabd24e51ab8.png)

Hi Jim, sorry for the late reply. I think I did a typo. Everything works fine :)
