### ISSUE TITLE
Borders and Frames

### ISSUE THREAD

**Issue by BoraSchninsky** [jimz011/homekit-infused#190]
![Screenshot_20221104_131444](https://user-images.githubusercontent.com/49289734/199971091-49c9e64d-42e2-4801-946d-3a13d37fc671.png)

hi..

since 
Home Assistant 2022.11.1
Supervisor 2022.10.2
Operating System 9.3
Frontend 20221102.1 - latest

i have borders around my menu and cards

can you help me?

**Comment by jimz011** [comment]
Yes, either do the following:
1. Downgrade to HA 2022.10.x
2. Wait for my update this weekend
3. Or change theme settings and then change border-style to none.

HA 2022.11.x is currently not fully supported yet

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Bora Schninsky ***@***.***>
Sent: Friday, November 4, 2022 1:20:30 PM
To: jimz011/homekit-infused ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [jimz011/homekit-infused] Borders and Frames (Issue #190)


[Screenshot_20221104_131444]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F49289734%2F199971091-49c9e64d-42e2-4801-946d-3a13d37fc671.png&data=05%7C01%7C%7C2b96ef96734e4f42c1a408dabe5ef792%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638031612330885465%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Htg9yBkUNixrmoxKMHkoGXErcVaGiFBvWaSYBHJsZUo%3D&reserved=0>

hi..

since
Home Assistant 2022.11.1
Supervisor 2022.10.2
Operating System 9.3
Frontend 20221102.1 - latest

i have borders around my menu and cards

can you help me?

**Comment by yaazzz** [comment]
Hi Jim, I tried this out without success. As it is only cosmetic it is not a real concern ;) 
Have a nice weekend.

**Comment by BoraSchninsky** [comment]
> Yes, either do the following: 1. Downgrade to HA 2022.10.x 2. Wait for my update this weekend 3. Or change theme settings and then change border-style to none. HA 2022.11.x is currently not fully supported yet Get Outlook for Android<https://aka.ms/AAb9ysg>
> […](#)
> ________________________________ From: Bora Schninsky ***@***.***> Sent: Friday, November 4, 2022 1:20:30 PM To: jimz011/homekit-infused ***@***.***> Cc: Subscribed ***@***.***> Subject: [jimz011/homekit-infused] Borders and Frames (Issue #190) [Screenshot_20221104_131444]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F49289734%2F199971091-49c9e64d-42e2-4801-946d-3a13d37fc671.png&data=05%7C01%7C%7C2b96ef96734e4f42c1a408dabe5ef792%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638031612330885465%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Htg9yBkUNixrmoxKMHkoGXErcVaGiFBvWaSYBHJsZUo%3D&reserved=0> hi.. since Home Assistant 2022.11.1 Supervisor 2022.10.2 Operating System 9.3 Frontend 20221102.1 - latest i have borders around my menu and cards can you help me? — Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjimz011%2Fhomekit-infused%2Fissues%2F190&data=05%7C01%7C%7C2b96ef96734e4f42c1a408dabe5ef792%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638031612330885465%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2Flabo%2FAaQvvDa55RrtYudVBeC6azQYVHfG459LRstgo%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FALG6BXSO2YVFBVX5P44R5EDWGT5Q5ANCNFSM6AAAAAARXD6YPQ&data=05%7C01%7C%7C2b96ef96734e4f42c1a408dabe5ef792%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638031612330885465%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=X0BXnmFkK6r%2FAIDDNeHDRDJ%2B36j31AXHA7aUJh5U1Fw%3D&reserved=0>. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Thank you

**Comment by jimz011** [comment]
Fixed in 2022.6.0
