### ISSUE TITLE
theme：HKI Custom Dark

### ISSUE THREAD

**Issue by 602293544** [jimz011/homekit-infused#192]
![Snipaste_2022-11-05_18-49-19](https://user-images.githubusercontent.com/54359412/200116284-2eca2936-5a3a-47ae-836b-fc165b503f67.png)

**Comment by jimz011** [comment]
Since a lot of theme variables are linked to each other it is impossible to make every theme work with the default card designer.
I suggest setting a light theme first, then use the card designer. Copy/paste the code and once done set it back to the dark theme.

HKI was not built with the card designer in mind (though I admit it is very useful).

**Comment by jimz011** [comment]
This has been fixed in v2022.6.1, closing this now
