### ISSUE TITLE
[FR]Nvidia Shield Remote Add-On Custom Buttons

### ISSUE THREAD

**Issue by MagicMountainMan** [jimz011/homekit-infused#45]
The Sheild remote works perfectly but an option to change the left buttons would be amazing. Right now the four buttons are Youtube, Plex, Netflix, and Spotify. If I was able to change the buttons to whatever I wanted that would make it perfect.

**Comment by jimz011** [comment]
The icons will be fixed in the next version, I guess I could make the icons customizable yeah (though it would still only be fixed to opening an app on your shield tv. Sorry). 

If you want more customization I suggest copying the template from the base to your user templates folder and edit it to your needs.

**Comment by MagicMountainMan** [comment]
Yeah just opening an app is perfect.

**Comment by jimz011** [comment]
This is added in 3.1.2. Closing this now!
