### ISSUE TITLE
calendar-card.js' but it does not exist

### ISSUE THREAD

**Issue by fredamn76** [jimz011/homekit-infused#50]
custom:calender-card is no longer maintained.
`as of hass 0.115 a built in calendar card is included so this card is archived and will no longer be developed. if any features are missing in the new card, open pull requests against lovelace to get them added.`

```
Logger: custom_components.hacs.web.category
Source: custom_components/hacs/webresponses/category.py:31
Integration: hacs (documentation, issues)
First occurred: 6:25:24 (2 occurrences)
Last logged: 6:43:45

Tried to serve up '/config/www/community/calendar-card/calendar-card.js' but it does not exist
```

**Comment by jimz011** [comment]
The custom calendar card is no longer used in HKI, it might still work though I will advise you to convert to the core calendar card instead https://github.com/jimz011/homekit-infused/blob/master/docs/addons/calendar-card.md

I will close this issue since the custom calendar card is going to deprecate in any case. If you still want to use the card I suggest visiting the original repo for that card.
