### ISSUE TITLE
[FR] Vacuum - return to base

### ISSUE THREAD

**Issue by donhimol** [jimz011/homekit-infused#55]
Do not know if it is common problem or only Xiaomi Vacuums but command vacuum.return_to_base does not work properly if vacuum is cleaning. After sending this command vacuum is pausing and hitting next time it is coming back.

Simple solution is to change service vacuum.return_to_base into i.e:
    - service: vacuum.pause
      entity_id: vacuum.roborock
    - delay: 1
    - service: vacuum.return_to_base
      entity_id: vacuum.roborock

**Comment by jimz011** [comment]
I will look into this, I have also noticed this!

**Comment by jimz011** [comment]
Unfortunately it doesn't seem like return_to_base does an actual return_to_base. I will look further into this as making an automation isn't quite simple (since your entity_id might vary from mine) and button-card doesn't allow me to add multiple services when pressed.

I will leave this open for now.

**Comment by jimz011** [comment]
This seems to be vacuum specific and there is nothing I can do about this. I will close this issue now.
