### ISSUE TITLE
[FR] Header with Back to Home option

### ISSUE THREAD

**Issue by evroekel** [jimz011/homekit-infused#56]
**Is your feature request related to a problem? Please describe.**
It feels a bit weird to have a home button on the bottom in the app. I'm continuously looking for a back to home in the top bar. 

**Describe the solution you'd like**
Add the option to place Home (icon or the word) in front of the Title and make that part clickable to home/the frontpage view. So more like a breadcrumb: Home | Title or Home > Title
And additional to this, make it possible to hide/delete the home icon on the bottom.

**Describe alternatives you've considered**

**Additional context**
-

**Comment by jimz011** [comment]
Sorry for the late response, since Custom Header will stop working in the near future I am looking for replacements. This might mean the footer will go anyway and will have to move the navigation buttons to the top. Though the original idea was, people with large phones will have a harder time reaching those buttons all the way at the top.

I am not entirely sure how I will handle this situation. But expect changes to it soon.

**Comment by jimz011** [comment]
I have decided to move the navigation to the top since Custom Header is deprecated. This will incorporate your wish and seemed the only logical way out (since I can no longer use CH).

See discord for screenshots.

**Comment by jimz011** [comment]
Added in 3.5.0 closing now!
