### ISSUE TITLE
[FR] using JSON-style definitions with jinja2 macros

### ISSUE THREAD

**Issue by lmamakos** [jimz011/homekit-infused#63]
Since you're using lovelace_gen as part of stitching together all the files, you might look at my post on the community site https://community.home-assistant.io/t/fun-with-lovelace-gen-and-jinja2-macros-to-avoid-whitespace-indentation-problems/236427 as it might be helpful.  Essentially, it makes the observation that you can use jinja2 macros to generate arbitrary lovelace configuration, regardless of the identation level by using JSON syntax.  The JSON lines don't require any indentation level.  Take a look and see if that might be helpful!

**Comment by jimz011** [comment]
I did see this in the past and yes it is helpful, though as you may or may not know, this project will only get essential updates and minor/major bugfixes, since it works pretty well and the project has changed a lot already (and I don't want people to get frustrated to change it once again).

Tbh this is the HKI version (v3 and up) without many breaking changes in quite some time which was essentially the goal. The next project is in production though because of the new jobs I just took they are slightly on hold. But the next big thing will be a native app for Android (and maybe iOS).

I will still thank you for this information and I might still implement it anyways.

**Comment by jimz011** [comment]
I have looked at it a few times, but HKI5 will have no use for this unfortunately. Will close this now!
