### ISSUE TITLE
[FR] Single Homekit Button that has mini-graph-card as the popup card

### ISSUE THREAD

**Issue by MagicMountainMan** [jimz011/homekit-infused#68]
**Is your feature request related to a problem? Please describe.**
I migrated from using the auto template for my temperature sensors to manually filling them out.

**Describe the solution you'd like**
I would like a way to be able to have the mini-graph-card still be available as the long press pop up as there is currently not a button template that allows for that.

**Describe alternatives you've considered**
Right now I'm just using the default more info popup with the ugly stock Home Assistant graph.

**Additional context**
Just like how you introduced the new template for the climate entity as its own button template, it would be great to have that for a sensor/whatever else uses graphs.

**Comment by jimz011** [comment]
I will close this issue since the answer to this question can be found in the mini-graph documentation. Although I am not sure if fire-dom-event is implemented in this card. What this means is that I do not know if this is possible. I personally use a button card and create a popup (fire-dom-event). You could extract the code from /templates/button/mini-graph.yaml and /templates/button/button.yaml and see if you can recreate it.
