### ISSUE TITLE
[FR] Thermostat Card Improvement - Show temperature range when set to heat_cool mode

### ISSUE THREAD

**Issue by Russell-A-Diehl** [jimz011/homekit-infused#77]
Jim,
Love the project, currently using the version 4.0.0c. Thanks for everything you do for the home-assistant community.

I noticed one small annoyance with the thermostat card and made a fix for it locally and figured I would share here in case you wanted to implement the changes if they make sense to you or if someone else browsing the repo ran across a similar issue. 

**Problem:**
When my thermostat (Ecobee) is set to 'heat_cool' mode the temperature values in the button comes up as "null" since the attributes.temperature variable used by the card is null.

**Background:**
For the Ecobee specifically, when the mode is set to heat_cool;
the temperature range is defined by the attributes

- _target_temp_low_
- _target_temp_high_

If the thermostat is set to heat mode or cool mode;
the target temperature is defined by the attribute

- _temperature_

**Solution:**
What I did to fix it on my end in the **hki-base/templates/button/thermostat.yaml** changed the following lines.

_**Part 1: Bottom Right Corner of Button - Target Temperatures**_
To get the bottom right corner to display correctly showing the temperature range when in heat_cool mode, the target temperature when in heat or cool mode, and the current thermostat temperature when no mode is set or the thermostat is off is

Change the following line from

> _aspect_ratio: {{ aspect_ratio|default('1/1') }}
> entity: {{ entity }}
> **label: "[[[ return \`${states['{{entity}}'].attributes.temperature}°\` ]]]"**_

to

> _aspect_ratio: {{ aspect_ratio|default('1/1') }}
> entity: {{ entity }}
> **label: "[[[ if (states['{{entity}}'].state == 'heat_cool') return \`${states['{{entity}}'].attributes.target_temp_low}° - ${states['{{entity}}'].attributes.target_temp_high}°\`; if (states['{{entity}}'].state == 'heat') return \`${states['{{entity}}'].attributes.temperature}°\`; if (states['{{entity}}'].state == 'cool') return \`${states['{{entity}}'].attributes.temperature}°\`; else return \`${states['{{entity}}'].attributes.current_temperature}°\` ]]]"**_

This looks through the current thermostat state and sets the bottom right text based on the mode the thermostat is currently set to. This could be simplified to a simple if/else statement looking only for heat_cool mode state, but I decided that I want to see the current temperature if the thermostat is not set to a specific mode (I may change this value to something else later but this is how I have it for now)

_**Part 2: Top Left Circle on Button - Show Current Temperature**_
Since I can't rely on the attributes.temperature value when I run my thermostat in heat_cool mode for half the year, I changed the top left icon to display the current temperature instead of the target temperature as it is currently configured to show.

I was able to do this by changing the following line from

> _custom_fields: 
>   **notification: "[[[ return \`${states['{{entity}}'].attributes.temperature}°\` ]]]"**_

to

> _custom_fields: 
>   **notification: "[[[ return \`${states['{{entity}}'].attributes.current_temperature}°\` ]]]"**_

I personally find this also makes a little more sense to show why the thermostat is heating or cooling by having both the current temperature and target temperatures shown on the card.

**End Result:**
The end result when in heat_cool mode looks like this

<img width="141" alt="Screen Shot 2021-04-26 at 17 30 33" src="https://user-images.githubusercontent.com/67616498/116153434-4a410a80-a6b5-11eb-946f-ed05b43dec15.png">

where the **top left in the circle always shows the current thermostat temperature reading**, and the **bottom right shows the target temperature(s)** depending on the mode.

*Disclaimer: This will get overwritten by any updates since it is a change made to a file in the hki-base folder.

**Comment by jimz011** [comment]
The current temperature attribute was a bug which slipped into v4 and will be fixed in the next update (it used to work fine). I will look at the provided cods and add it if it works, since I have never accounted for heat_cool before.

Thank you and I will test this soon

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
From: Russell Diehl ***@***.***>
Sent: Tuesday, April 27, 2021 2:54:20 AM
To: jimz011/homekit-infused ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [jimz011/homekit-infused] [FR] Thermostat Card Improvement - Show temperature range when set to heat_cool mode (#77)


Jim,
Love the project, currently using the version 4.0.0c. Thanks for everything you do for the home-assistant community.

I noticed one small annoyance with the thermostat card and made a fix for it locally and figured I would share here in case you wanted to implement the changes if they make sense to you or if someone else browsing the repo ran across a similar issue.

Problem:
When my thermostat (Ecobee) is set to 'heat_cool' mode the temperature values in the button comes up as "null" since the attributes.temperature variable used by the card is null.

Background:
For the Ecobee specifically, when the mode is set to heat_cool;
the temperature range is defined by the attributes

  *   target_temp_low
  *   target_temp_high

If the thermostat is set to heat mode or cool mode;
the target temperature is defined by the attribute

  *   temperature

Solution:
What I did to fix it on my end in the hki-base/templates/button/thermostat.yaml changed the following lines.

Part 1: Bottom Right Corner of Button - Target Temperatures
To get the bottom right corner to display correctly showing the temperature range when in heat_cool mode, the target temperature when in heat or cool mode, and the current thermostat temperature when no mode is set or the thermostat is off is

Change the following line from

aspect_ratio: {{ aspect_ratio|default('1/1') }}
entity: {{ entity }}
label: "[[[ return `${states['{{entity}}'].attributes.temperature}°` ]]]"

to

aspect_ratio: {{ aspect_ratio|default('1/1') }}
entity: {{ entity }}
label: "[[[ if (states['{{entity}}'].state == 'heat_cool') return `${states['{{entity}}'].attributes.target_temp_low}° - ${states['{{entity}}'].attributes.target_temp_high}°`; if (states['{{entity}}'].state == 'heat') return `${states['{{entity}}'].attributes.temperature}°`; if (states['{{entity}}'].state == 'cool') return `${states['{{entity}}'].attributes.temperature}°`; else return `${states['{{entity}}'].attributes.current_temperature}°` ]]]"

This looks through the current thermostat state and sets the bottom right text based on the mode the thermostat is currently set to. This could be simplified to a simple if/else statement looking only for heat_cool mode state, but I decided that I want to see the current temperature if the thermostat is not set to a specific mode (I may change this value to something else later but this is how I have it for now)

Part 2: Top Left Circle on Button - Show Current Temperature
Since I can't rely on the attributes.temperature value when I run my thermostat in heat_cool mode for half the year, I changed the top left icon to display the current temperature instead of the target temperature as it is currently configured to show.

I was able to do this by changing the following line from

custom_fields:
notification: "[[[ return `${states['{{entity}}'].attributes.temperature}°` ]]]"

to

custom_fields:
notification: "[[[ return `${states['{{entity}}'].attributes.current_temperature}°` ]]]"

I personally find this also makes a little more sense to show why the thermostat is heating or cooling by having both the current temperature and target temperatures shown on the card.

End Result:
The end result when in heat_cool mode looks like this

[Screen Shot 2021-04-26 at 17 30 33]<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F67616498%2F116153434-4a410a80-a6b5-11eb-946f-ed05b43dec15.png&data=04%7C01%7C%7C290c94c834b64dfa4e0c08d90916fe6d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637550816619211212%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=hySloQfyiwdgZxXKvif5mEv4UwdbzaQl5kZYA%2FM1nKw%3D&reserved=0>

where the top left in the circle always shows the current thermostat temperature reading, and the bottom right shows the target temperature(s) depending on the mode.

*Disclaimer: This will get overwritten by any updates since it is a change made to a file in the hki-base folder.

**Comment by jimz011** [comment]
This looks cool, I will add this in the next release

**Comment by jimz011** [comment]
Closing this as this has been merged for v4.0.0e
