### ISSUE TITLE
Duplicated keys in base.yaml

### ISSUE THREAD

**Issue by E020** [jimz011/homekit-infused#78]
<img width="918" alt="duplicated key" src="https://user-images.githubusercontent.com/57673156/116678281-6db3d000-a9a9-11eb-8f7f-38c036f5084e.png">

This is logged in the HA logfile. I didn't change anything in the base.yaml file or other HKI-files. Known issue?

Just to be clear: Everything seems to be working fine ;-)

**Comment by jimz011** [comment]
Not a known issue, I will need to take a look into this since most of the stuff is conditional. You would help me if you would send me your view_config file

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
From: E020 ***@***.***>
Sent: Friday, April 30, 2021 11:47:18 AM
To: jimz011/homekit-infused ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [jimz011/homekit-infused] Duplicated keys in base.yaml (#78)


[duplicated key]<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F57673156%2F116678281-6db3d000-a9a9-11eb-8f7f-38c036f5084e.png&data=04%7C01%7C%7Cbd9ac1d14a6549c6bbf908d90bbcf206%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637553728397739359%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=f7ONVyzSfGN2fjvVuC1C09Ks5xiweuVjhDopf%2FlWrY4%3D&reserved=0>

This is logged in the HA logfile. I didn't change anything in the base.yaml file or other HKI-files. Known issue?

**Comment by E020** [comment]
[view_config.txt](https://github.com/jimz011/homekit-infused/files/6404799/view_config.txt)

Attached as txt file, because yaml was not supported.

**Comment by jimz011** [comment]
I found the problem, will fix it thanks for mentioning it

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by jimz011** [comment]
I forgot to fix this, expect it to have high prio for the next release

**Comment by jimz011** [comment]
Should be gone in the next release, I haven't seen the issue anymore, please reopen this if it does after updating to 4.0.0e (release somewhere this weekend)
