### ISSUE TITLE
[FR] Friendly name option for Entity card add-on

### ISSUE THREAD

**Issue by E020** [jimz011/homekit-infused#95]
https://www.home-assistant.io/lovelace/entity/ has the option for a friendly name.
Unfortunately https://jimz011.github.io/homekit-infused/addons-v4/entities.html doesn't support this yet.

**Comment by jimz011** [comment]
Yes this is a known problem, but also mentioned in the docs of this addon. Entities card is way too powerful to template it and to put in even just a few options that that card can do will drastically drive up the lines of code used.

I will suggest creating a custom view with this card if you desire the options that this card can do. Or.... you can use addons and Custom cards on the same view.

This might look awkward on a tablet or desktop unless you use addons and Custom cards in a specific way.

Below 2 usecases that might help you mix them:
1. Use a view selector (this basically splits a view up and thus you could have a addon view and a custom view, though still have the feeling that it is a single view.
2. Use the max amount of stacks in addons as your view supports (e.g. 1080p usually takes a max of 4 stacks horizontally without changing the layout code or 3 when the sidebar is expanded). So, having an addon (or 4 single addons) that each take up a space horizontally will make those custom cards look great, since well.... they will be put below the last stack. In this case since the first row is filled with addons, custom cards will come on the second row. Similarly of  if you would use 8 addon stacks or 12 etc.

Since this will only affect tablets and laptops you could theoretically plan your layout a bit. I am still looking for a way to place custom cards in the next slot, but if I do so it will break the current folder/file structure of custom cards. Doing that will currently require the user to refer to each file they want as a custom card, and each file could only take one card, where ofc a stack (e.g. vertical or horizontal is treated as a single card as well). Each file would need to be defined in the view config.yaml file manually (whereas now you have the choice between putting each card in a single file, or having multiple files with single cards or mix with one file having several cards and other files as well with just dropping those files within their respective folders).

I think it would make HKI very complicated for users that use custom views a lot (some of them only use custom views and just want the framework). It would also be a massive breaking change for anyone that used v3 and just migrated with their custom views (since v3 didnt have any built in addons they were basically only custom views).

It wouldn't be the biggest deal to make it, though it would probably give me more trouble than I am actually solving. The custom cards section is something I added so that people with wishes I either can't fulfill or that are simply too hard or too much to template can still create whatever they want.

To slightly mitigate the "problem" of people not knowing yaml very well, there is the sandbox in the HKI settings, which is basically just the default lovelace UI card builder. It can't save cards for you, however you can easily copy/paste the code from the card you just created and drop it into your custom cards folder.

But..... since I do find it annoying myself, I will continue the search for a feasible solution without breaking how it currently works.

**Comment by E020** [comment]
Well that makes sense. It’s much bigger then I expected. So a fully understand your decision and will take a look at the suggestions. 

Thx!
